// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    public partial class Log
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Int64 Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String Name {set;get;}
    }

}
// It's the end
