// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace Model
{
    [System.ComponentModel.DataAnnotations.Schema.Table("Log",Schema ="dbo")]
    public partial class Log
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Int64 Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String Name {set;get;}
    }

}
