// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// Tb_Company(公司信息表)
    /// <summary>
    public class Tb_Company
    {
        /// <summary>
        ///企业ID
        /// </summary>
        public Guid EnterpriseID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///企业名称
        /// </summary>
        [XString(100,true)]
        public String EnterpriseName {set;get;}
        /// <summary>
        ///企业法人
        /// </summary>
        [XString(50,true)]
        public String LegalPerson {set;get;}
        /// <summary>
        ///所属行业
        /// </summary>
        [XString(100,true)]
        public String Industry {set;get;}
        /// <summary>
        ///公司类型
        /// </summary>
        [XString(100,true)]
        public String CompanyType {set;get;}
        /// <summary>
        ///企业类型
        /// </summary>
        [XString(100,true)]
        public String EnterpriseType {set;get;}
        /// <summary>
        ///公司属性
        /// </summary>
        [XString(50,true)]
        public String CompanyAttribute {set;get;}
        /// <summary>
        ///成立时间
        /// </summary>
        public Nullable<DateTime> SetUpTime {set;get;}
        /// <summary>
        ///是否家族企业
        /// </summary>
        public Boolean IsFamily {set;get;}
        /// <summary>
        ///注册资本
        /// </summary>
        public Nullable<Decimal> RegisterCapital {set;get;}
        /// <summary>
        ///销售资本
        /// </summary>
        public Nullable<Decimal> SaleCapital {set;get;}
        /// <summary>
        ///人数规模
        /// </summary>
        public Nullable<Int32> CompanyScale {set;get;}
        /// <summary>
        ///公司地址
        /// </summary>
        [XString(-1,true)]
        public String CompanyAddress {set;get;}
        /// <summary>
        ///公司编号
        /// </summary>
        [XString(200,true)]
        public String CompanyNo {set;get;}
    }
}
// It's the end
