// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// Tb_Department(部门信息表)
    /// <summary>
    public class Tb_Department
    {
        /// <summary>
        ///部门ID
        /// </summary>
        public Guid DepartmentID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///企业ID
        /// </summary>
        public Nullable<Guid> EnterpriseID {set;get;}
        /// <summary>
        ///部门名称
        /// </summary>
        [XString(100,true)]
        public String DepartmentName {set;get;}
        /// <summary>
        ///上级部门名称
        /// </summary>
        [XString(100,true)]
        public String HigheDepartment {set;get;}
        /// <summary>
        ///上级部门ID
        /// </summary>
        public Nullable<Guid> HigheDepartmentID {set;get;}
        /// <summary>
        ///部门层级
        /// </summary>
        public Nullable<Int32> ClassLayer {set;get;}
    }
}
// It's the end
