// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_Employee
    {
        /// <summary>
        ///员工ID
        /// </summary>
        public Guid EmployeeID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///员工姓名
        /// </summary>
        [XString(100,true)]
        public String EmployeeName {set;get;}
        /// <summary>
        ///部门ID
        /// </summary>
        public Nullable<Guid> DepartmentID {set;get;}
        /// <summary>
        ///岗位ID
        /// </summary>
        public Nullable<Guid> PostID {set;get;}
        /// <summary>
        ///头像
        /// </summary>
        public Byte[] Avatar {set;get;}
        /// <summary>
        ///手机号
        /// </summary>
        [XString(100,true)]
        public String Mobile {set;get;}
        /// <summary>
        ///工龄
        /// </summary>
        [XString(100,true)]
        public String JobAge {set;get;}
        /// <summary>
        ///职级
        /// </summary>
        [XString(100,true)]
        public String Rank {set;get;}
        /// <summary>
        ///年薪
        /// </summary>
        [XString(100,true)]
        public String AnnualSalary {set;get;}
        /// <summary>
        ///入职时间
        /// </summary>
        public Nullable<DateTime> EntryTime {set;get;}
        /// <summary>
        ///企业ID
        /// </summary>
        public Nullable<Guid> EnterpriseID {set;get;}
        /// <summary>
        ///
        /// </summary>
        [XString(100,true)]
        public String EmployeeNum {set;get;}
    }
}
// It's the end
