// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// 评估中考虑的因素
    /// <summary>
    public class Tb_EvaluatedFactor
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///股权分配Id
        /// </summary>
        public Guid ShareHoldingId {set;get;}
        /// <summary>
        ///因素名称
        /// </summary>
        public String FactorName {set;get;}
        /// <summary>
        ///因素权重
        /// </summary>
        public Decimal FactorRate {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///描述
        /// </summary>
        [XString(-1,true)]
        public String Remark {set;get;}
    }
}
// It's the end
