// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// 评估人信息
    /// <summary>
    public class Tb_EvaluatingMaster
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///股权分配Id
        /// </summary>
        public Guid ShareHoldingId {set;get;}
        /// <summary>
        ///基础信息人员Id
        /// </summary>
        public Guid EmployeeID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///是否完成评估 0-未完成，1-完成
        /// </summary>
        public Nullable<Int32> CompleteEvaluating {set;get;}
        /// <summary>
        ///评估人姓名 （如果姓名重复则加上索引）
        /// </summary>
        [XString(200,true)]
        public String Name {set;get;}
    }
}
// It's the end
