// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// 待评估的岗位信息
    /// <summary>
    public class Tb_EvaluatedPostion
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///股权分配Id
        /// </summary>
        public Guid ShareHoldingId {set;get;}
        /// <summary>
        ///基础信息岗位Id
        /// </summary>
        public Guid PositionId {set;get;}
        /// <summary>
        ///岗位人数（在计算方式是岗位的情况下）
        /// </summary>
        public Int32 NumberOfPost {set;get;}
        /// <summary>
        ///岗位分数（评估结果的平均分）
        /// </summary>
        public Int32 Score {set;get;}
        /// <summary>
        ///实际分配股数（在计算方式是岗位的情况下）
        /// </summary>
        public Int32 FinalShareValue {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///所属部门
        /// </summary>
        public Guid DepartmentID {set;get;}
    }
}
// It's the end
