// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// Tb_IncentiveObject(激励对象持股平台)
    /// <summary>
    public class Tb_IncentiveObject
    {
        /// <summary>
        ///主键
        /// </summary>
        public Guid PrimaryID {set;get;}
        /// <summary>
        ///激励对象ID
        /// </summary>
        public Guid IncentiveID {set;get;}
        /// <summary>
        ///股东表主键ID
        /// </summary>
        public Guid PartnerPrimaryID {set;get;}
        /// <summary>
        ///激励岗位
        /// </summary>
        [XString(200,true)]
        public String IncentivePost {set;get;}
        /// <summary>
        ///激励对象姓名
        /// </summary>
        [XString(200,true)]
        public String IncentiveName {set;get;}
        /// <summary>
        ///激励数量
        /// </summary>
        public Nullable<Decimal> IncentiveNum {set;get;}
        /// <summary>
        ///持股比例
        /// </summary>
        public Nullable<Decimal> HoldPercent {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
    }
}
// It's the end
