// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// Tb_MeasureProgram(测算方案表)
    /// <summary>
    public class Tb_MeasureProgram
    {
        /// <summary>
        ///方案ID
        /// </summary>
        public Guid ProgramID {set;get;}
        /// <summary>
        ///方案名称
        /// </summary>
        [XString(100,true)]
        public String ProgramName {set;get;}
        /// <summary>
        ///公司类型 是否股份公司
        /// </summary>
        public Boolean IsShares {set;get;}
        /// <summary>
        ///公司名称
        /// </summary>
        [XString(100,true)]
        public String CompanyName {set;get;}
        /// <summary>
        ///所属行业
        /// </summary>
        [XString(100,true)]
        public String Industry {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///公司ID
        /// </summary>
        public Nullable<Guid> EnterpriseID {set;get;}
    }
}
// It's the end
