// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_MeasurePartner
    {
        /// <summary>
        ///主键ID
        /// </summary>
        public Guid PrimaryID {set;get;}
        /// <summary>
        ///股份数量
        /// </summary>
        public Nullable<Int32> SharesCount {set;get;}
        /// <summary>
        ///股东ID
        /// </summary>
        public Nullable<Guid> PartnerID {set;get;}
        /// <summary>
        ///测算ID
        /// </summary>
        public Nullable<Guid> MeasureID {set;get;}
        /// <summary>
        ///股东类型
        /// </summary>
        [XString(200,true)]
        public String PartnerType {set;get;}
        /// <summary>
        ///股东名称
        /// </summary>
        [XString(200,true)]
        public String PartnerName {set;get;}
        /// <summary>
        ///比例
        /// </summary>
        public Nullable<Decimal> PartnerPercent {set;get;}
        /// <summary>
        ///方案ID
        /// </summary>
        public Nullable<Guid> ProgramID {set;get;}
        /// <summary>
        ///转让方式ID
        /// </summary>
        public Nullable<Guid> TransferWayID {set;get;}
        /// <summary>
        ///转让方式
        /// </summary>
        [XString(100,true)]
        public String TransferWay {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///股东类型ID
        /// </summary>
        public Nullable<Guid> PartnerTypeID {set;get;}
    }
}
// It's the end
