// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// 
    /// <summary>
    public class Tb_Member
    {
        /// <summary>
        ///
        /// </summary>
        public Int32 ID {set;get;}
        /// <summary>
        ///
        /// </summary>
        [XString(50,true)]
        public String MemberID {set;get;}
        /// <summary>
        ///
        /// </summary>
        [XString(50,true)]
        public String Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> CreateTime {set;get;}
    }
}
// It's the end
