// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// Tb_Mechanism(机构信息表)
    /// <summary>
    public class Tb_Mechanism
    {
        /// <summary>
        ///机构ID
        /// </summary>
        public Guid MechanismID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///机构名称
        /// </summary>
        [XString(200,true)]
        public String MechanismName {set;get;}
        /// <summary>
        ///是否股份公司
        /// </summary>
        public Boolean IsShares {set;get;}
        /// <summary>
        ///股份数量
        /// </summary>
        public Nullable<Int64> SharesNum {set;get;}
        /// <summary>
        ///成立时间
        /// </summary>
        public Nullable<DateTime> SetupTime {set;get;}
        /// <summary>
        ///备注
        /// </summary>
        [XString(-1,true)]
        public String Remark {set;get;}
        /// <summary>
        ///上级机构ID
        /// </summary>
        public Nullable<Guid> ParentBodyID {set;get;}
        /// <summary>
        ///上级机构
        /// </summary>
        [XString(-1,true)]
        public String ParentBody {set;get;}
        /// <summary>
        ///上级控股比例
        /// </summary>
        public Nullable<Decimal> ParentHoldPercent {set;get;}
        /// <summary>
        ///上级控股数量
        /// </summary>
        public Nullable<Int64> ParentHoldCoun {set;get;}
        /// <summary>
        ///层级
        /// </summary>
        public Int32 ClassLayer {set;get;}
        /// <summary>
        ///是否为特殊机构
        /// </summary>
        public Boolean IsSpecial {set;get;}
        /// <summary>
        ///结构ID
        /// </summary>
        public Nullable<Guid> StructureID {set;get;}
    }
}
// It's the end
