// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_News
    {
        /// <summary>
        ///新闻ID
        /// </summary>
        public Guid NewID {set;get;}
        /// <summary>
        ///标题
        /// </summary>
        [XString(100,true)]
        public String Title {set;get;}
        /// <summary>
        ///图片URL
        /// </summary>
        [XString(500,true)]
        public String ImgUrl {set;get;}
        /// <summary>
        ///分类ID
        /// </summary>
        public Nullable<Guid> CategoryID {set;get;}
        /// <summary>
        ///分类名称
        /// </summary>
        [XString(100,true)]
        public String CategoryName {set;get;}
        /// <summary>
        ///来源
        /// </summary>
        [XString(200,true)]
        public String Source {set;get;}
        /// <summary>
        ///概要
        /// </summary>
        [XString(500,true)]
        public String Summary {set;get;}
        /// <summary>
        ///内容
        /// </summary>
        [XString(2147483647,true)]
        public String Content {set;get;}
        /// <summary>
        ///发布时间
        /// </summary>
        public Nullable<DateTime> ReleaseTime {set;get;}
        /// <summary>
        ///发布人
        /// </summary>
        public Nullable<Guid> ReleaseUserID {set;get;}
        /// <summary>
        ///发布状态
        /// </summary>
        public Nullable<Boolean> ReleaseStatus {set;get;}
        /// <summary>
        ///排序
        /// </summary>
        public Nullable<Int32> Sort {set;get;}
        /// <summary>
        ///浏览量
        /// </summary>
        public Nullable<Int32> PageView {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
    }
}
// It's the end
