// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    /// <summary>
    /// 岗位评估分数明细
    /// <summary>
    public class Tb_PostionScoreDetail
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///待评估岗位的Id
        /// </summary>
        public Guid PostionScoreId {set;get;}
        /// <summary>
        ///分数
        /// </summary>
        public Int32 Score {set;get;}
        /// <summary>
        ///岗位价值因素（影响，沟通，知识，创新）-于IPE保持一致
        /// </summary>
        public Int32 PositionFactor {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///
        /// </summary>
        public String PositionFactorItem {set;get;}
    }
}
// It's the end
