// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_PostionScore
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///待评估岗位的Id
        /// </summary>
        public Guid EvaluatedPositionId {set;get;}
        /// <summary>
        ///评估人员Id
        /// </summary>
        public Guid EvaluatingMasterId {set;get;}
        /// <summary>
        ///分数
        /// </summary>
        public Int32 Score {set;get;}
        /// <summary>
        ///股权分配Id(冗余列，避免表连接)
        /// </summary>
        public Guid ShareHoldingId {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///备注
        /// </summary>
        public String Remark {set;get;}
        /// <summary>
        ///职等
        /// </summary>
        public String PositionLevel {set;get;}
    }
}
// It's the end
