// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_PeopleScore
    {
        /// <summary>
        ///Id
        /// </summary>
        public Guid Id {set;get;}
        /// <summary>
        ///因素Id
        /// </summary>
        public Guid FactorId {set;get;}
        /// <summary>
        ///待评估人员Id
        /// </summary>
        public Guid EvaluatedPeopleId {set;get;}
        /// <summary>
        ///评估人员Id
        /// </summary>
        public Guid EvaluatingMasterId {set;get;}
        /// <summary>
        ///分数
        /// </summary>
        public Decimal Score {set;get;}
        /// <summary>
        ///股权分配Id(冗余列，避免表连接)
        /// </summary>
        public Guid ShareHoldingId {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
    }
}
// It's the end
