// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_Quota
    {
        /// <summary>
        ///主键
        /// </summary>
        public Guid PrimaryID {set;get;}
        /// <summary>
        ///指标ID
        /// </summary>
        public Nullable<Guid> QuotaID {set;get;}
        /// <summary>
        ///测算ID
        /// </summary>
        public Nullable<Guid> MeasureID {set;get;}
        /// <summary>
        ///指标名称
        /// </summary>
        [XString(100,true)]
        public String QuotaName {set;get;}
        /// <summary>
        ///指标值
        /// </summary>
        [XString(100,true)]
        public String QuotaValue {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///指标类型（1:销售,2:利润,3:市盈利,0:其他）
        /// </summary>
        public Int32 QuotaType {set;get;}
    }
}
// It's the end
