// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_Shareholde
    {
        /// <summary>
        ///股东ID
        /// </summary>
        public Guid ShareholdeID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///持股机构
        /// </summary>
        [XString(100,true)]
        public String HoldMechanism {set;get;}
        /// <summary>
        ///持股比例
        /// </summary>
        public Nullable<Decimal> HoldPercent {set;get;}
        /// <summary>
        ///持股数量
        /// </summary>
        public Nullable<Int32> HoldCoun {set;get;}
        /// <summary>
        ///股东类别ID
        /// </summary>
        public Nullable<Guid> HoldCategoryID {set;get;}
        /// <summary>
        ///股东类别
        /// </summary>
        [XString(100,true)]
        public String HoldCategoryName {set;get;}
        /// <summary>
        ///股东名称
        /// </summary>
        [XString(200,true)]
        public String HoldName {set;get;}
        /// <summary>
        ///股东属性ID
        /// </summary>
        public Nullable<Guid> HoldAttributeID {set;get;}
        /// <summary>
        ///股东属性
        /// </summary>
        [XString(100,true)]
        public String HoldAttributeName {set;get;}
        /// <summary>
        ///是否股份公司
        /// </summary>
        public Boolean IsShares {set;get;}
        /// <summary>
        ///股份数量
        /// </summary>
        public Nullable<Int32> SharesCount {set;get;}
        /// <summary>
        ///入股时间
        /// </summary>
        public Nullable<DateTime> ShareTime {set;get;}
        /// <summary>
        ///备注
        /// </summary>
        [XString(300,true)]
        public String Remark {set;get;}
        /// <summary>
        ///父级ID
        /// </summary>
        public Nullable<Guid> ParentID {set;get;}
        /// <summary>
        ///层级
        /// </summary>
        public Nullable<Int32> ClassLayer {set;get;}
        /// <summary>
        ///结构ID
        /// </summary>
        public Nullable<Guid> StructureID {set;get;}
    }
}
// It's the end
