// Code generated by a template
using System;
using Azeroth.Nalu;
namespace T4
{
    public class Tb_Structure
    {
        /// <summary>
        ///结构ID
        /// </summary>
        public Guid StructureID {set;get;}
        /// <summary>
        ///创建时间
        /// </summary>
        public DateTime CreateTime {set;get;}
        /// <summary>
        ///创建人ID
        /// </summary>
        public Guid Creator {set;get;}
        /// <summary>
        ///修改时间
        /// </summary>
        public Nullable<DateTime> LastModiTime {set;get;}
        /// <summary>
        ///修改人
        /// </summary>
        public Nullable<Guid> LastModifier {set;get;}
        /// <summary>
        ///是否删除
        /// </summary>
        public Boolean IsDel {set;get;}
        /// <summary>
        ///结构名称
        /// </summary>
        [XString(200,true)]
        public String StructureName {set;get;}
        /// <summary>
        ///公司企业ID
        /// </summary>
        public Nullable<Guid> EnterpriseID {set;get;}
        /// <summary>
        ///公司企业名称
        /// </summary>
        [XString(100,true)]
        public String EnterpriseName {set;get;}
        /// <summary>
        ///是否股份公司
        /// </summary>
        public Boolean IsShares {set;get;}
        /// <summary>
        ///股份数量
        /// </summary>
        public Int32 SharesNum {set;get;}
        /// <summary>
        ///预测时间
        /// </summary>
        public Nullable<DateTime> PredictionDate {set;get;}
        /// <summary>
        ///是否默认架构
        /// </summary>
        public Boolean IsDefault {set;get;}
        /// <summary>
        ///是否实际控股
        /// </summary>
        public Boolean IsActualHold {set;get;}
        /// <summary>
        ///实际控股人(股份表主键)
        /// </summary>
        public Nullable<Guid> ActualHoldID {set;get;}
        /// <summary>
        ///实际控股人名
        /// </summary>
        [XString(100,true)]
        public String ActualHoldName {set;get;}
        /// <summary>
        ///实际控股人股百分比
        /// </summary>
        public Nullable<Decimal> ActualHoldNumShares {set;get;}
        /// <summary>
        ///实际控股人股数
        /// </summary>
        public Nullable<Int32> ActualHoldNum {set;get;}
    }
}
// It's the end
